// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apistore.proto

package apistore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpenAPI struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenAPI) Reset()         { *m = OpenAPI{} }
func (m *OpenAPI) String() string { return proto.CompactTextString(m) }
func (*OpenAPI) ProtoMessage()    {}
func (*OpenAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{0}
}

func (m *OpenAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAPI.Unmarshal(m, b)
}
func (m *OpenAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAPI.Marshal(b, m, deterministic)
}
func (m *OpenAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAPI.Merge(m, src)
}
func (m *OpenAPI) XXX_Size() int {
	return xxx_messageInfo_OpenAPI.Size(m)
}
func (m *OpenAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAPI.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAPI proto.InternalMessageInfo

func (m *OpenAPI) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateAPIRes struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	API                  *API     `protobuf:"bytes,3,opt,name=API,proto3" json:"API,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAPIRes) Reset()         { *m = CreateAPIRes{} }
func (m *CreateAPIRes) String() string { return proto.CompactTextString(m) }
func (*CreateAPIRes) ProtoMessage()    {}
func (*CreateAPIRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{1}
}

func (m *CreateAPIRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAPIRes.Unmarshal(m, b)
}
func (m *CreateAPIRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAPIRes.Marshal(b, m, deterministic)
}
func (m *CreateAPIRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAPIRes.Merge(m, src)
}
func (m *CreateAPIRes) XXX_Size() int {
	return xxx_messageInfo_CreateAPIRes.Size(m)
}
func (m *CreateAPIRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAPIRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAPIRes proto.InternalMessageInfo

func (m *CreateAPIRes) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateAPIRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateAPIRes) GetAPI() *API {
	if m != nil {
		return m.API
	}
	return nil
}

type API struct {
	APIID                string    `protobuf:"bytes,1,opt,name=APIID,proto3" json:"APIID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Methods              []*Method `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	Schemas              []*Ref    `protobuf:"bytes,5,rep,name=schemas,proto3" json:"schemas,omitempty"`
	Servers              []*Server `protobuf:"bytes,6,rep,name=servers,proto3" json:"servers,omitempty"`
	Title                string    `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *API) Reset()         { *m = API{} }
func (m *API) String() string { return proto.CompactTextString(m) }
func (*API) ProtoMessage()    {}
func (*API) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{2}
}

func (m *API) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_API.Unmarshal(m, b)
}
func (m *API) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_API.Marshal(b, m, deterministic)
}
func (m *API) XXX_Merge(src proto.Message) {
	xxx_messageInfo_API.Merge(m, src)
}
func (m *API) XXX_Size() int {
	return xxx_messageInfo_API.Size(m)
}
func (m *API) XXX_DiscardUnknown() {
	xxx_messageInfo_API.DiscardUnknown(m)
}

var xxx_messageInfo_API proto.InternalMessageInfo

func (m *API) GetAPIID() string {
	if m != nil {
		return m.APIID
	}
	return ""
}

func (m *API) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *API) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *API) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *API) GetSchemas() []*Ref {
	if m != nil {
		return m.Schemas
	}
	return nil
}

func (m *API) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *API) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Server struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Description          map[string]string `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{3}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Server) GetDescription() map[string]string {
	if m != nil {
		return m.Description
	}
	return nil
}

type Method struct {
	MethodID             string   `protobuf:"bytes,1,opt,name=methodID,proto3" json:"methodID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Data                 *Data    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	RefNames             []string `protobuf:"bytes,5,rep,name=refNames,proto3" json:"refNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{4}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetMethodID() string {
	if m != nil {
		return m.MethodID
	}
	return ""
}

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Method) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Method) GetRefNames() []string {
	if m != nil {
		return m.RefNames
	}
	return nil
}

type Data struct {
	Params               string   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Return               string   `protobuf:"bytes,2,opt,name=return,proto3" json:"return,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{5}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *Data) GetReturn() string {
	if m != nil {
		return m.Return
	}
	return ""
}

type Ref struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema               string   `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d158277b2bcf3f1, []int{6}
}

func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (m *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(m, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ref) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenAPI)(nil), "OpenAPI")
	proto.RegisterType((*CreateAPIRes)(nil), "CreateAPIRes")
	proto.RegisterType((*API)(nil), "API")
	proto.RegisterType((*Server)(nil), "Server")
	proto.RegisterMapType((map[string]string)(nil), "Server.DescriptionEntry")
	proto.RegisterType((*Method)(nil), "Method")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Ref)(nil), "Ref")
}

func init() { proto.RegisterFile("apistore.proto", fileDescriptor_1d158277b2bcf3f1) }

var fileDescriptor_1d158277b2bcf3f1 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x8a, 0x13, 0x31,
	0x14, 0x66, 0xda, 0xe9, 0x4c, 0x7b, 0xea, 0xca, 0x12, 0xa5, 0xc4, 0x22, 0x52, 0xc7, 0x9b, 0xe2,
	0xc5, 0x94, 0xad, 0x20, 0xda, 0x0b, 0xa1, 0xd8, 0xbd, 0x18, 0xf0, 0xa7, 0x64, 0x9f, 0x20, 0xb6,
	0xa7, 0xdd, 0x61, 0x3b, 0xc9, 0x90, 0xa4, 0x85, 0xde, 0xfa, 0x06, 0x22, 0xf8, 0x46, 0x3e, 0x81,
	0xaf, 0xe0, 0x83, 0x48, 0x7e, 0xa6, 0x56, 0xd9, 0xbb, 0xf3, 0x7d, 0x39, 0xf9, 0xf2, 0xe5, 0x4b,
	0x0e, 0x3c, 0xe4, 0x75, 0xa9, 0x8d, 0x54, 0x98, 0xd7, 0x4a, 0x1a, 0x39, 0x7c, 0xba, 0x95, 0x72,
	0xbb, 0xc3, 0x09, 0xaf, 0xcb, 0x09, 0x17, 0x42, 0x1a, 0x6e, 0x4a, 0x29, 0xb4, 0x5f, 0xcd, 0x5e,
	0x40, 0xfa, 0xb9, 0x46, 0x31, 0x5f, 0x16, 0x84, 0x42, 0xba, 0x92, 0xc2, 0xa0, 0x30, 0x34, 0x1a,
	0x45, 0xe3, 0x1e, 0x6b, 0x60, 0xf6, 0x01, 0x1e, 0xbc, 0x57, 0xc8, 0x0d, 0xce, 0x97, 0x05, 0x43,
	0x4d, 0x08, 0xc4, 0x2b, 0xb9, 0xc6, 0xd0, 0xe6, 0x6a, 0x72, 0x09, 0xed, 0x4a, 0x6f, 0x69, 0xcb,
	0x51, 0xb6, 0x24, 0x03, 0x68, 0xcf, 0x97, 0x05, 0x6d, 0x8f, 0xa2, 0x71, 0x7f, 0x1a, 0xe7, 0x76,
	0xaf, 0x25, 0xb2, 0x9f, 0x91, 0x5b, 0x20, 0x8f, 0xa1, 0x33, 0x5f, 0x16, 0xc5, 0x22, 0xc8, 0x78,
	0x60, 0xb5, 0x05, 0xaf, 0x30, 0x08, 0xb9, 0xda, 0x3a, 0x3b, 0xa0, 0xd2, 0xa5, 0x14, 0x4e, 0xad,
	0xc7, 0x1a, 0x48, 0x9e, 0x43, 0x5a, 0xa1, 0xb9, 0x95, 0x6b, 0x4d, 0xe3, 0x51, 0x7b, 0xdc, 0x9f,
	0xa6, 0xf9, 0x47, 0x87, 0x59, 0xc3, 0x93, 0x67, 0x90, 0xea, 0xd5, 0x2d, 0x56, 0x5c, 0xd3, 0x8e,
	0x6b, 0x89, 0x73, 0x86, 0x1b, 0xd6, 0x90, 0x56, 0x42, 0xa3, 0xb2, 0x82, 0x34, 0x09, 0x12, 0x37,
	0x0e, 0xb3, 0x86, 0xb7, 0x4e, 0x4d, 0x69, 0x76, 0x48, 0x53, 0xef, 0xd4, 0x81, 0xec, 0x47, 0x04,
	0x89, 0xef, 0xb4, 0x97, 0xdf, 0xab, 0x5d, 0xb8, 0x88, 0x2d, 0xc9, 0x0c, 0xfa, 0x6b, 0xd4, 0x2b,
	0x55, 0xd6, 0x36, 0x6d, 0xda, 0x72, 0xca, 0x34, 0x28, 0xe7, 0x8b, 0xbf, 0x4b, 0xd7, 0xc2, 0xa8,
	0x23, 0x3b, 0x6f, 0x1e, 0xbe, 0x83, 0xcb, 0xff, 0x1b, 0xec, 0x09, 0x77, 0x78, 0x6c, 0x4e, 0xb8,
	0xc3, 0xa3, 0x35, 0x75, 0xe0, 0xbb, 0x7d, 0x93, 0x94, 0x07, 0xb3, 0xd6, 0x9b, 0x28, 0xfb, 0x16,
	0x41, 0xe2, 0x53, 0x20, 0x43, 0xe8, 0xfa, 0x1c, 0x4e, 0x31, 0x9f, 0xf0, 0xbd, 0x49, 0x8f, 0xfe,
	0xb5, 0xed, 0xd3, 0x3e, 0xa7, 0xc8, 0x13, 0x88, 0xd7, 0xdc, 0x70, 0x1a, 0xbb, 0x67, 0xed, 0xe4,
	0x0b, 0x6e, 0x38, 0x73, 0x94, 0x3d, 0x4c, 0xe1, 0xe6, 0x13, 0xaf, 0xd0, 0x47, 0xdd, 0x63, 0x27,
	0x9c, 0xbd, 0x86, 0xd8, 0x76, 0x92, 0x01, 0x24, 0x35, 0x57, 0xbc, 0xd2, 0xc1, 0x4e, 0x40, 0x96,
	0x57, 0x68, 0xf6, 0x4a, 0x04, 0x3b, 0x01, 0x65, 0x57, 0xd0, 0x66, 0xb8, 0x39, 0x79, 0x8d, 0xce,
	0xbc, 0x0e, 0x20, 0xf1, 0x6f, 0xd8, 0x6c, 0xf1, 0x68, 0x7a, 0x0d, 0xdd, 0xf9, 0xb2, 0xb8, 0xb1,
	0x23, 0x40, 0xde, 0x42, 0xef, 0xf4, 0x73, 0x49, 0x37, 0x0f, 0x5f, 0x7d, 0x78, 0x91, 0x9f, 0xff,
	0xe7, 0xec, 0xd1, 0xd7, 0x5f, 0xbf, 0xbf, 0xb7, 0x2e, 0xb2, 0xee, 0xe4, 0x70, 0x65, 0xe7, 0x44,
	0xcf, 0xa2, 0x97, 0x5f, 0x12, 0x37, 0x20, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xa5,
	0xba, 0x50, 0x50, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIStoreClient is the client API for APIStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIStoreClient interface {
	// 导入API
	CreateAPI(ctx context.Context, in *OpenAPI, opts ...grpc.CallOption) (*CreateAPIRes, error)
}

type aPIStoreClient struct {
	cc *grpc.ClientConn
}

func NewAPIStoreClient(cc *grpc.ClientConn) APIStoreClient {
	return &aPIStoreClient{cc}
}

func (c *aPIStoreClient) CreateAPI(ctx context.Context, in *OpenAPI, opts ...grpc.CallOption) (*CreateAPIRes, error) {
	out := new(CreateAPIRes)
	err := c.cc.Invoke(ctx, "/APIStore/CreateAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIStoreServer is the server API for APIStore service.
type APIStoreServer interface {
	// 导入API
	CreateAPI(context.Context, *OpenAPI) (*CreateAPIRes, error)
}

// UnimplementedAPIStoreServer can be embedded to have forward compatible implementations.
type UnimplementedAPIStoreServer struct {
}

func (*UnimplementedAPIStoreServer) CreateAPI(ctx context.Context, req *OpenAPI) (*CreateAPIRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPI not implemented")
}

func RegisterAPIStoreServer(s *grpc.Server, srv APIStoreServer) {
	s.RegisterService(&_APIStore_serviceDesc, srv)
}

func _APIStore_CreateAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenAPI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIStoreServer).CreateAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/APIStore/CreateAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIStoreServer).CreateAPI(ctx, req.(*OpenAPI))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "APIStore",
	HandlerType: (*APIStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAPI",
			Handler:    _APIStore_CreateAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apistore.proto",
}
